preferences-automatically-sync-on-profile-openclose = Automatically sync on profile open/close
preferences-backups = Backups
preferences-change-deck-depending-on-note-type = Change deck depending on note type
preferences-changes-will-take-effect-when-you = Changes will take effect when you restart Clanki.
preferences-hours-past-midnight = hours past midnight
preferences-language = Language
preferences-interrupt-current-audio-when-answering = Interrupt current audio when answering
preferences-learn-ahead-limit = Learn ahead limit
preferences-mins = mins
preferences-network = Syncing
preferences-next-day-starts-at = Next day starts at
preferences-media-is-not-backed-up = Media is not backed up. Please create a periodic backup of your Clanki folder to be safe.
preferences-on-next-sync-force-changes-in = On next sync, force changes in one direction
preferences-paste-clipboard-images-as-png = Paste clipboard images as PNG
preferences-paste-without-shift-key-strips-formatting = Paste without shift key strips formatting
preferences-generate-latex-images-automatically = Generate LaTeX images (security risk)
preferences-latex-generation-disabled = LaTeX image generation is disabled in the preferences.
preferences-periodically-sync-media = Periodically sync media
preferences-please-restart-anki-to-complete-language = Please restart Clanki to complete language change.
preferences-preferences = Preferences
preferences-scheduling = Scheduling
preferences-show-learning-cards-with-larger-steps = Show learning cards with larger steps before reviews
preferences-show-next-review-time-above-answer = Show next review time above answer buttons
preferences-show-colored-buttons = Show colored border on answer buttons
preferences-two-button-mode = Show only Again and Good answer buttons
preferences-show-fuzz-delta-above-answer-buttons = Show fuzz delta next to answer button intervals
preferences-show-review-heatmap = Show the review heatmap
preferences-heatmap-tab = Review Heatmap
preferences-heatmap-appearance = Appearance
preferences-heatmap-color-scheme = Color scheme
preferences-heatmap-calendar-mode = Calendar mode
preferences-heatmap-visibility = Show the heatmap on
preferences-heatmap-on-deck-list = Main screen (deck list)
preferences-heatmap-on-overview = Deck screen
preferences-heatmap-on-stats = Stats screen (Shift+click Stats)
preferences-heatmap-streak-always = Show the streak figures even where the heatmap is hidden
preferences-heatmap-history = History and forecast
preferences-heatmap-limits-tooltip = Applies to the main screen and the deck screen; the stats screen follows its own period.
preferences-heatmap-history-limit = History limit
preferences-heatmap-forecast-limit = Forecast limit
preferences-heatmap-no-limit = No limit
# The forecast limit's lowest setting: the heatmap never forecasts more
# than 5 years ahead.
preferences-heatmap-forecast-five-years = 5 years
preferences-heatmap-days = days
preferences-heatmap-ignore-before = Ignore reviews before
preferences-heatmap-exclude-deleted = Exclude deleted cards from the history
preferences-heatmap-exclude-rescheduled = Exclude manual reschedules from the history
preferences-heatmap-excluded-decks = Decks left out of the main-screen heatmap
preferences-heatmap-excluded-decks-tooltip = These decks and their subdecks are not counted on the main screen. Each deck's own heatmap still counts them.
preferences-heatmap-add-deck = Add...
preferences-heatmap-remove-deck = Remove
preferences-heatmap-addon-disabled = The Review Heatmap add-on has been disabled, because Clanki now shows the review heatmap itself. Its settings are in Preferences > Review Heatmap.
preferences-heatmap-addon-blocked = Clanki already has the Review Heatmap built in, so the add-on stays disabled. Its settings are in Preferences > Review Heatmap.
preferences-ankiconnect-tab = AnkiConnect
preferences-ankiconnect-enabled = Turn on AnkiConnect
preferences-ankiconnect-explanation = AnkiConnect lets other programs, such as Yomitan, browser extensions and scripts, read and change this collection through a local web server. It speaks the same protocol as the AnkiConnect add-on, so they need no change.
preferences-ankiconnect-server = Server
preferences-ankiconnect-bind-address = Address
preferences-ankiconnect-bind-address-tooltip = 127.0.0.1 accepts connections from this computer only. 0.0.0.0 accepts them from every computer that can reach this one.
preferences-ankiconnect-port = Port
preferences-ankiconnect-access = Access
preferences-ankiconnect-cors-origins = Allowed web origins, one per line
preferences-ankiconnect-cors-origins-tooltip = Web pages and browser extensions from these origins may use AnkiConnect. "http://localhost" also admits 127.0.0.1 and browser extensions; "*" admits every web page. Programs that are not web pages are always admitted.
preferences-ankiconnect-api-key = API key
preferences-ankiconnect-api-key-placeholder = None: no key required
preferences-ankiconnect-api-key-tooltip = When set, every request must carry this key.
preferences-ankiconnect-status-off = AnkiConnect is off.
preferences-ankiconnect-status-starting = AnkiConnect is starting.
preferences-ankiconnect-status-listening = Listening on { $address }:{ $port }.
preferences-ankiconnect-status-port-in-use = Port { $port } on { $address } is in use by another program (another Anki with AnkiConnect?). Clanki tries again every few seconds.
preferences-ankiconnect-status-error = AnkiConnect cannot listen on { $address }:{ $port }: { $error }. Clanki tries again every few seconds.
preferences-ankiconnect-port-in-use = AnkiConnect cannot start: port { $port } on { $address } is in use by another program. Clanki tries again every few seconds; you can choose another port in Preferences > AnkiConnect.
preferences-ankiconnect-addon-disabled = The AnkiConnect add-on has been disabled, because Clanki now has AnkiConnect built in and has turned it on, with the add-on's settings. They are in Preferences > AnkiConnect.
preferences-ankiconnect-addon-blocked = Clanki already has AnkiConnect built in, so the add-on stays disabled. The built-in AnkiConnect is now on; its settings are in Preferences > AnkiConnect.
preferences-fsrs-helper-addon-disabled = The FSRS Helper add-on has been disabled, because it is not compatible with FSRS-7, the version of FSRS that Clanki uses.
preferences-fsrs-helper-addon-blocked = The FSRS Helper add-on is not compatible with FSRS-7, the version of FSRS that Clanki uses, so it stays disabled.
preferences-ankiconnect-permission-title = A website wants to access Clanki
preferences-ankiconnect-permission-text = "{ $origin }" requests permission to use Clanki through AnkiConnect. Do you want to give it access?
preferences-ankiconnect-permission-details = By granting permission, you'll allow the website to modify your collection on your behalf, including the execution of destructive actions such as deck deletion.
preferences-ankiconnect-permission-ignore = Ignore further requests from "{ $origin }"
preferences-spacebar-rates-card = Spacebar (or enter) also answers card
preferences-show-play-buttons-on-cards-with = Show play buttons on cards with audio
preferences-show-remaining-card-count = Show remaining card count
preferences-some-settings-will-take-effect-after = Some settings will take effect after you restart Clanki.
preferences-tab-synchronisation = Synchronization
preferences-synchronize-audio-and-images-too = Synchronize audio and images too
preferences-login-successful-sync-now = Log-in successful. Save preferences and sync now?
preferences-timebox-time-limit = Timebox time limit
preferences-user-interface-size = User interface size
preferences-when-adding-default-to-current-deck = When adding, default to current deck
preferences-you-can-restore-backups-via-fileswitch = You can restore backups via File > Switch Profile.
preferences-legacy-timezone-handling = Legacy timezone handling (buggy, but required for AnkiDroid <= 2.14)
preferences-default-search-text = Default search text
preferences-default-search-text-example = e.g. "deck:current"
preferences-theme = Theme
preferences-theme-follow-system = Follow System
preferences-theme-light = Light
preferences-theme-dark = Dark
preferences-v3-scheduler = V3 scheduler
preferences-updates = Updates
preferences-check-for-updates = Check for program updates
preferences-check-for-addon-updates = Check for add-on updates
preferences-ignore-accents-in-search = Ignore accents in search (slower)
preferences-backup-explanation =
    Clanki periodically backs up your collection. After backups are more than 2 days old,
    Clanki will start removing some of them to free up disk space.
preferences-daily-backups = Daily backups to keep:
preferences-weekly-backups = Weekly backups to keep:
preferences-monthly-backups = Monthly backups to keep:
preferences-minutes-between-backups = Minutes between automatic backups:
preferences-reduce-motion = Reduce motion
preferences-reduce-motion-tooltip = Disable various animations and transitions of the user interface
preferences-custom-sync-url = Self-hosted sync server
preferences-custom-sync-url-disclaimer = For advanced users - please see the manual
preferences-hide-top-bar-during-review = Hide top bar during review
preferences-hide-bottom-bar-during-review = Hide bottom bar during review
preferences-always = Always
preferences-full-screen-only = Full screen only
preferences-appearance = Appearance
preferences-general = General
preferences-style = Style
preferences-review = Review
preferences-answer-keys = Answer keys
preferences-distractions = Distractions
preferences-minimalist-mode = Minimalist mode
preferences-minimalist-mode-tooltip = Make the interface more compact/less fancy
preferences-editing = Editing
preferences-browsing = Browsing
preferences-default-deck = Default deck
preferences-account = AnkiWeb Account
preferences-note = Note
preferences-scheduler = Scheduler
preferences-user-interface = User Interface
preferences-import-export = Import/Export
preferences-network-timeout = Network timeout
preferences-reset-window-sizes = Reset Window Sizes
preferences-reset-window-sizes-complete = Window sizes and locations have been reset.
preferences-shortcut-placeholder = Enter an unused shortcut key, or leave empty to disable.
preferences-third-party-services = Third-Party Services
preferences-ankihub-not-logged-in = Not currently logged in to AnkiHub.
preferences-ankiweb-intro = AnkiWeb is a free service that lets you keep your flashcard data in sync across your devices, and provides a way to recover the data if your device breaks or is lost.
preferences-ankihub-intro = AnkiHub provides collaborative deck editing and additional study tools. A paid subscription is required to access certain features.
preferences-third-party-description = Third-party services are unaffiliated with and not endorsed by Anki. Use of these services may require payment.
preferences-experimental-features-tab = Experiments

## URL scheme related
preferences-url-schemes = URL Schemes
preferences-url-scheme-prompt = Allowed URL Schemes (space-separated):
preferences-url-scheme-warning = Blocked attempt to open `{ $link }`, which may be a security issue.

    If you trust the deck author and wish to proceed, you can add `{ $scheme }` to your allowed URL Schemes.
preferences-url-scheme-allow-once = Allow Once
preferences-url-scheme-always-allow = Always Allow

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Basic
preferences-reviewer = Reviewer
preferences-media = Media
preferences-not-logged-in = Not currently logged in to AnkiWeb.
